# Generated by Django 5.1.7 on 2025-04-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_weightadjustmentlog_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anbar_Muhavateh_Homayound',
            new_name='Anbar_Muhavateh_Homayoun',
        ),
        migrations.AlterModelOptions(
            name='anbar_muhavateh_homayoun',
            options={'verbose_name_plural': 'Anbar Muhavateh Homayoun'},
        ),
        migrations.AlterModelTable(
            name='anbar_muhavateh_homayoun',
            table='Anbar_Muhavateh_Homayoun',
        ),
    ]
