# Generated by Django 4.2.10 on 2024-03-07 16:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("status", models.CharField(blank=True, max_length=255)),
                ("comments", models.TextField(blank=True)),
                ("logs", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="MaterialType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("material_type", models.CharField(max_length=255)),
                ("username", models.CharField(blank=True, max_length=255)),
                (
                    "date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("logs", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reel_number", models.CharField(max_length=255)),
                ("width", models.IntegerField()),
                ("gsm", models.IntegerField()),
                ("length", models.IntegerField()),
                ("grade", models.CharField(max_length=255)),
                ("breaks", models.CharField(max_length=255)),
                ("comments", models.TextField(blank=True, null=True)),
                ("qr_code", models.TextField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(default="Anbar_Salon_Tolid", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In-stock", "In-stock"),
                            ("Sold", "Sold"),
                            ("Moved", "Moved"),
                            ("Delivered", "Delivered"),
                        ],
                        default="In-stock",
                        max_length=50,
                    ),
                ),
                ("receive_date", models.DateTimeField(blank=True, null=True)),
                ("last_date", models.DateTimeField(blank=True, null=True)),
                (
                    "profile_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("logs", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "Products",
            },
        ),
        migrations.CreateModel(
            name="Shipments",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "shipment_type",
                    models.CharField(
                        choices=[("Incoming", "Incoming"), ("Outgoing", "Outgoing")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Registered", "Registered"),
                            ("LoadingUnloading", "LoadingUnloading"),
                            ("LoadedUnloaded", "LoadedUnloaded"),
                            ("Offiffice", "Offiffice"),
                            ("Delivered", "Delivered"),
                            ("Canceled", "Canceled"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Entrance", "Entrance"),
                            ("Weight1", "Weight1"),
                            ("Weight2", "Weight2"),
                            ("Offiffice", "Offiffice"),
                            ("Delivered", "Delivered"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("truck_id", models.IntegerField(null=True)),
                ("license_number", models.CharField(max_length=255, null=True)),
                ("receive_date", models.DateTimeField(blank=True, null=True)),
                ("entry_time", models.DateTimeField(blank=True, null=True)),
                ("customer_name", models.CharField(max_length=255, null=True)),
                ("supplier_name", models.CharField(max_length=255, null=True)),
                (
                    "weight1",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("weight1_time", models.DateTimeField(blank=True, null=True)),
                ("unload_location", models.CharField(max_length=255, null=True)),
                ("unit", models.CharField(max_length=255, null=True)),
                ("quantity", models.IntegerField(null=True)),
                ("quality", models.CharField(max_length=255, null=True)),
                ("penalty", models.CharField(max_length=255, null=True)),
                (
                    "weight2",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("weight2_time", models.DateTimeField(blank=True, null=True)),
                ("net_weight", models.CharField(max_length=10, null=True)),
                ("list_of_reels", models.TextField(null=True)),
                ("profile_name", models.CharField(max_length=255, null=True)),
                ("sales_id", models.IntegerField(null=True)),
                (
                    "price_per_kg",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "extra_cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("supplier_id", models.IntegerField(null=True)),
                ("material_id", models.IntegerField(null=True)),
                ("material_type", models.CharField(max_length=255, null=True)),
                ("material_name", models.CharField(max_length=255, null=True)),
                ("purchase_id", models.IntegerField(null=True)),
                (
                    "vat",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "invoice_status",
                    models.CharField(
                        choices=[
                            ("NA", "NA"),
                            ("Sent", "Sent"),
                            ("Received", "Received"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("Terms", "Terms"), ("Paid", "Paid")],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("document_info", models.TextField(null=True)),
                ("comments", models.TextField(null=True)),
                ("cancellation_reason", models.TextField(null=True)),
                ("logs", models.TextField(blank=True)),
            ],
            options={"db_table": "Shipments",},
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("supplier_name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("status", models.CharField(blank=True, max_length=255)),
                ("comments", models.TextField(blank=True)),
                ("logs", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=255, unique=True)),
                ("driver_name", models.CharField(blank=True, max_length=255)),
                ("driver_doc", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("Free", "Free"), ("Busy", "Busy")],
                        default="Free",
                        max_length=10,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("username", models.TextField(blank=True)),
                ("logs", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("material_type", models.CharField(max_length=255)),
                ("unit_name", models.CharField(max_length=255, unique=True)),
                ("count", models.FloatField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=255)),
                (
                    "date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("logs", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(null=True)),
                ("license_number", models.CharField(max_length=255, null=True)),
                ("list_of_reels", models.TextField(null=True)),
                ("profile_name", models.CharField(max_length=255, null=True)),
                (
                    "weight1",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "weight2",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "net_weight",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "price_per_kg",
                    models.DecimalField(decimal_places=0, max_digits=10, null=True),
                ),
                (
                    "vat",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "extra_cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "invoice_status",
                    models.CharField(
                        choices=[("Sent", "Sent"), ("NA", "NA")],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Terms", "Terms"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("payment_details", models.CharField(max_length=255, null=True)),
                ("payment_date", models.DateTimeField(null=True)),
                ("document_info", models.TextField(null=True)),
                ("comments", models.TextField(null=True)),
                ("cancellation_reason", models.TextField(null=True)),
                ("logs", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.customer",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.shipments",
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.truck",
                    ),
                ),
            ],
            options={"db_table": "Sales",},
        ),
        migrations.CreateModel(
            name="RawMaterial",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("material_type", models.CharField(max_length=255)),
                ("material_name", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("comments", models.TextField(blank=True)),
                ("logs", models.TextField(blank=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raw_materials",
                        to="myapp.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purchases",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("receive_date", models.DateTimeField(blank=True, null=True)),
                (
                    "material_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("unit", models.CharField(blank=True, max_length=255, null=True)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("quality", models.CharField(blank=True, max_length=255, null=True)),
                ("penalty", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "weight1",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "weight2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_per_kg",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                (
                    "vat",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "extra_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "invoice_status",
                    models.CharField(
                        blank=True,
                        choices=[("Received", "Received"), ("NA", "NA")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Paid", "Paid"),
                            ("Terms", "Terms"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=225,
                        null=True,
                    ),
                ),
                (
                    "payment_details",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("document_info", models.TextField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                ("logs", models.TextField(blank=True)),
                (
                    "material_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.materialtype",
                    ),
                ),
                (
                    "shipment_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.shipments",
                    ),
                ),
                (
                    "supplier_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.supplier",
                    ),
                ),
                (
                    "truck_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.truck",
                    ),
                ),
            ],
            options={"db_table": "Purchases",},
        ),
        migrations.CreateModel(
            name="Consumption",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("receive_date", models.DateTimeField(blank=True, null=True)),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("unit", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "reel_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "profile_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("logs", models.TextField(blank=True)),
                (
                    "supplier_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Anbar_Sangin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("receive_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reel_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("In-stock", "In-stock"),
                            ("Sold", "Sold"),
                            ("Moved", "Moved"),
                            ("Used", "Used"),
                            ("Canceled", "Canceled"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="Entrance", max_length=255, null=True
                    ),
                ),
                ("last_date", models.DateTimeField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("gsm", models.IntegerField(blank=True, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=255, null=True)),
                ("breaks", models.CharField(blank=True, max_length=255, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("qr_code", models.TextField(blank=True, null=True)),
                (
                    "profile_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("logs", models.TextField(blank=True)),
                (
                    "supplier_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.supplier",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Anbar Sangin", "abstract": False,},
        ),
        migrations.CreateModel(
            name="Anbar_Salon_Tolid",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("receive_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reel_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("In-stock", "In-stock"),
                            ("Sold", "Sold"),
                            ("Moved", "Moved"),
                            ("Used", "Used"),
                            ("Canceled", "Canceled"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="Entrance", max_length=255, null=True
                    ),
                ),
                ("last_date", models.DateTimeField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("gsm", models.IntegerField(blank=True, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=255, null=True)),
                ("breaks", models.CharField(blank=True, max_length=255, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("qr_code", models.TextField(blank=True, null=True)),
                (
                    "profile_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("logs", models.TextField(blank=True)),
                (
                    "supplier_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.supplier",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Anbar Salon Tolid", "abstract": False,},
        ),
        migrations.CreateModel(
            name="Anbar_Parvandeh",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("receive_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reel_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("In-stock", "In-stock"),
                            ("Sold", "Sold"),
                            ("Moved", "Moved"),
                            ("Used", "Used"),
                            ("Canceled", "Canceled"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="Entrance", max_length=255, null=True
                    ),
                ),
                ("last_date", models.DateTimeField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("gsm", models.IntegerField(blank=True, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=255, null=True)),
                ("breaks", models.CharField(blank=True, max_length=255, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("qr_code", models.TextField(blank=True, null=True)),
                (
                    "profile_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("logs", models.TextField(blank=True)),
                (
                    "supplier_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.supplier",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Anbar Parvandeh", "abstract": False,},
        ),
        migrations.CreateModel(
            name="Anbar_Muhvateh_Kardan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("receive_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reel_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("In-stock", "In-stock"),
                            ("Sold", "Sold"),
                            ("Moved", "Moved"),
                            ("Used", "Used"),
                            ("Canceled", "Canceled"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="Entrance", max_length=255, null=True
                    ),
                ),
                ("last_date", models.DateTimeField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("gsm", models.IntegerField(blank=True, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=255, null=True)),
                ("breaks", models.CharField(blank=True, max_length=255, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("qr_code", models.TextField(blank=True, null=True)),
                (
                    "profile_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("logs", models.TextField(blank=True)),
                (
                    "supplier_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Anbar Muhvateh Kardan",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Anbar_Koochak",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("receive_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reel_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("In-stock", "In-stock"),
                            ("Sold", "Sold"),
                            ("Moved", "Moved"),
                            ("Used", "Used"),
                            ("Canceled", "Canceled"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="Entrance", max_length=255, null=True
                    ),
                ),
                ("last_date", models.DateTimeField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("gsm", models.IntegerField(blank=True, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=255, null=True)),
                ("breaks", models.CharField(blank=True, max_length=255, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("qr_code", models.TextField(blank=True, null=True)),
                (
                    "profile_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("logs", models.TextField(blank=True)),
                (
                    "supplier_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.supplier",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Anbar Koochak", "abstract": False,},
        ),
        migrations.CreateModel(
            name="Anbar_Khamir_Kordan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("receive_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reel_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("In-stock", "In-stock"),
                            ("Sold", "Sold"),
                            ("Moved", "Moved"),
                            ("Used", "Used"),
                            ("Canceled", "Canceled"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="Entrance", max_length=255, null=True
                    ),
                ),
                ("last_date", models.DateTimeField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("gsm", models.IntegerField(blank=True, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=255, null=True)),
                ("breaks", models.CharField(blank=True, max_length=255, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("qr_code", models.TextField(blank=True, null=True)),
                (
                    "profile_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("logs", models.TextField(blank=True)),
                (
                    "supplier_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.supplier",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Anbar Khamir Kordan", "abstract": False,},
        ),
        migrations.CreateModel(
            name="Anbar_Khamir_Ghadim",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("receive_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reel_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("In-stock", "In-stock"),
                            ("Sold", "Sold"),
                            ("Moved", "Moved"),
                            ("Used", "Used"),
                            ("Canceled", "Canceled"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="Entrance", max_length=255, null=True
                    ),
                ),
                ("last_date", models.DateTimeField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("gsm", models.IntegerField(blank=True, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=255, null=True)),
                ("breaks", models.CharField(blank=True, max_length=255, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("qr_code", models.TextField(blank=True, null=True)),
                (
                    "profile_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("logs", models.TextField(blank=True)),
                (
                    "supplier_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.supplier",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Anbar Khamir Ghadim", "abstract": False,},
        ),
        migrations.CreateModel(
            name="Anbar_Akhal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("receive_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reel_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("In-stock", "In-stock"),
                            ("Sold", "Sold"),
                            ("Moved", "Moved"),
                            ("Used", "Used"),
                            ("Canceled", "Canceled"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="Entrance", max_length=255, null=True
                    ),
                ),
                ("last_date", models.DateTimeField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("gsm", models.IntegerField(blank=True, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=255, null=True)),
                ("breaks", models.CharField(blank=True, max_length=255, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("qr_code", models.TextField(blank=True, null=True)),
                (
                    "profile_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("logs", models.TextField(blank=True)),
                (
                    "supplier_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.supplier",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Anbar Akhal", "abstract": False,},
        ),
    ]
