# Generated by Django 5.1.7 on 2025-03-27 19:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anbar_Muhavateh_Homayoun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('In-stock', 'In-stock'), ('Sold', 'Sold'), ('Moved', 'Moved'), ('Used', 'Used'), ('Cancelled', 'Cancelled')], max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('receive_date', models.DateTimeField(blank=True, null=True)),
                ('last_date', models.DateTimeField(blank=True, null=True)),
                ('reel_number', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('material_type', models.CharField(blank=True, max_length=255, null=True)),
                ('material_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('gsm', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('breaks', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('logs', models.TextField(blank=True)),
                ('shipment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.shipments')),
            ],
            options={
                'verbose_name_plural': 'Anbar Muhavateh Homayoun',
                'db_table': 'Anbar_Muhavateh_Homayoun',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Anbar_PAK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('In-stock', 'In-stock'), ('Sold', 'Sold'), ('Moved', 'Moved'), ('Used', 'Used'), ('Cancelled', 'Cancelled')], max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('receive_date', models.DateTimeField(blank=True, null=True)),
                ('last_date', models.DateTimeField(blank=True, null=True)),
                ('reel_number', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('material_type', models.CharField(blank=True, max_length=255, null=True)),
                ('material_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('gsm', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('breaks', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('logs', models.TextField(blank=True)),
                ('shipment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.shipments')),
            ],
            options={
                'verbose_name_plural': 'Anbar PAK',
                'db_table': 'Anbar_PAK',
                'abstract': False,
            },
        ),
    ]
