# Generated by Django 4.2.10 on 2024-03-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anbar_akhal",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="anbar_khamir_ghadim",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="anbar_khamir_kordan",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="anbar_koochak",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="anbar_muhvateh_kardan",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="anbar_parvandeh",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="anbar_salon_tolid",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="anbar_sangin",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="consumption",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="materialtype",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="purchases",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="rawmaterial",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sales",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="shipments",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterModelTable(name="anbar_akhal", table="Anbar_Akhal",),
        migrations.AlterModelTable(
            name="anbar_khamir_ghadim", table="Anbar_Khamir_Ghadim",
        ),
        migrations.AlterModelTable(
            name="anbar_khamir_kordan", table="Anbar_Khamir_Kordan",
        ),
        migrations.AlterModelTable(name="anbar_koochak", table="Anbar_Koochak",),
        migrations.AlterModelTable(
            name="anbar_muhvateh_kardan", table="Anbar_Muhvateh_Kardan",
        ),
        migrations.AlterModelTable(name="anbar_parvandeh", table="Anbar_Parvandeh",),
        migrations.AlterModelTable(
            name="anbar_salon_tolid", table="Anbar_Salon_Tolid",
        ),
        migrations.AlterModelTable(name="anbar_sangin", table="Anbar_Sangin",),
        migrations.AlterModelTable(name="consumption", table="Consumption",),
        migrations.AlterModelTable(name="customer", table="Customer",),
        migrations.AlterModelTable(name="materialtype", table="MaterialType",),
        migrations.AlterModelTable(name="rawmaterial", table="RawMaterial",),
        migrations.AlterModelTable(name="supplier", table="Supplier",),
        migrations.AlterModelTable(name="truck", table="Truck",),
        migrations.AlterModelTable(name="unit", table="Unit",),
    ]
