# Generated by Django 5.1.7 on 2025-04-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_anbar_muhavateh_homayoun_anbar_pak'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightAdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('original_weight', models.CharField(max_length=50)),
                ('adjusted_weight', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(default='weight_adjustment', max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RenameModel(
            old_name='Anbar_Muhavateh_Homayoun',
            new_name='Anbar_Muhavateh_Homayound',
        ),
        migrations.AlterModelOptions(
            name='anbar_muhavateh_homayound',
            options={'verbose_name_plural': 'Anbar Muhavateh Homayound'},
        ),
        migrations.AlterModelTable(
            name='anbar_muhavateh_homayound',
            table='Anbar_Muhavateh_Homayound',
        ),
    ]
