# Generated by Django 4.2.10 on 2024-03-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_supplier_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="anbar_akhal",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="anbar_khamir_ghadim",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="anbar_khamir_kordan",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="anbar_koochak",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="anbar_muhvateh_kardan",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="anbar_parvandeh",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="anbar_salon_tolid",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="anbar_sangin",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="consumption",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="products",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="purchases",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="rawmaterial",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sales",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="shipments",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="truck",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
