# Generated by Django 4.2.10 on 2024-03-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_anbar_akhal_username_anbar_khamir_ghadim_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipments",
            name="status",
            field=models.CharField(
                choices=[
                    ("Registered", "Registered"),
                    ("LoadingUnloading", "LoadingUnloading"),
                    ("LoadedUnloaded", "LoadedUnloaded"),
                    ("Office", "Office"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
