# Generated by Django 4.2.10 on 2024-03-10 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_shipments_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
