from django.urls import path
from .views import *

urlpatterns = [
    path("api/apiHandler", apiHandler),
    path("api/checkLicenseNumber", check_license_number),
    path("api/addTruck", add_truck),
    path("addTruck/", add_truck),
    path("addSupplier/", add_supplier),
    path("addCustomer/", add_customer),
    path("api/getMaterialTypes", get_materialTypes),
    path("api/getSupplierNames", get_supplierNames),
    path("addRawMaterial/", add_rawMaterial),
    path("api/getConsumptionProfileNames", get_consumption_profile_names),
    path("api/addNewReel", add_new_reel),
    path("api/getLicenseNumbers", get_license_numbers),
    path("api/getMaterialNames", get_material_names),
    path("api/addShipment", add_shipment),
    path("api/updateWeight1", update_weight1),
    path("api/updateWeight2", update_weight2),
    path("api/createPurchaseOrder", create_purchase_order),
    path("api/createSalesOrder", create_sales_order),
    path("api/unload", unload),
    path("api/loaded", loaded),
    path("api/used", used),
    path("api/moved", moved),
    path("api/addNewAnbar", add_new_anbar),
    path("api/addMaterialType", add_material_type),
    path("api/addUnit", add_unit),
    path("api/addConsumptionProfile", add_consumption_profile),
    path("api/cancelShipment", cancel_shipment),
]
